namespace:
  name: demo
spec:
  replicas: 3
image:
  repository: nginx
  tag: alpine
  policy: IfNotPresent
resources:
  requests:
    cpu: 50m
    memory: 256Mi
service:
  type: ClusterIP
  port: 8111
configmap:
  data: "version: alpine"